const namespace = 'authenticate'

export const USER_AUTHENTICATION_REQUESTED = `${namespace}/USER_AUTHENTICATION_REQUESTED`
export const USER_AUTHENTICATION_SUCCEEDED = `${namespace}/USER_AUTHENTICATION_SUCCEEDED`
export const USER_AUTHENTICATION_FAILED = `${namespace}/USER_AUTHENTICATION_FAILED`

export const AUTHENTICATE_USER = [USER_AUTHENTICATION_REQUESTED, USER_AUTHENTICATION_SUCCEEDED, USER_AUTHENTICATION_FAILED]
